// GENERATED by scripts/build-insight-index.mjs — do not edit by hand.
// Regenerate after adding or changing an insight:
//   node scripts/build-insight-index.mjs

/**
 * Insight metadata, safe to import from client components.
 *
 * lib/insights.ts statically imports every article module, so importing it
 * from a "use client" file ships every article body in that page's bundle.
 * The dashboard is entirely client components and only ever needs the
 * metadata, so it reads this instead. Sorted newest first.
 */
export interface InsightIndexEntry {
  slug: string;
  title: string;
  description: string;
  ticker: string | null;
  postType: "pick" | "quarterly_review";
  publishedAt: string;
  readingTime: number;
}

export const INSIGHT_INDEX: readonly InsightIndexEntry[] = [
  {
    slug: "wdc-western-digital-ai-storage",
    title: "Stock buy: Western Digital is the AI era’s mass-capacity storage pick",
    description: "Post-split Western Digital is a pure-play HDD franchise riding hyperscale AI data growth — with record margins, long-term customer agreements, and a repaired balance sheet.",
    ticker: "WDC",
    postType: "pick",
    publishedAt: "2026-07-17",
    readingTime: 8,
  },
  {
    slug: "skwd-skyward-specialty-pc-insurer",
    title: "Stock buy: Skyward Specialty is building a broader specialty P&C platform",
    description: "Skyward Specialty underwrites niche commercial risks in the U.S. and, via Apollo, at Lloyd’s — a specialty insurer diversifying premium and fee income after a transformative acquisition.",
    ticker: "SKWD",
    postType: "pick",
    publishedAt: "2026-07-02",
    readingTime: 7,
  },
  {
    slug: "asic-ategrity-specialty-insurance-es",
    title: "Stock buy: Ategrity is industrializing E&S underwriting for SMBs",
    description: "Ategrity Specialty focuses on excess-and-surplus insurance for small and mid-sized businesses — a tech-enabled underwriting platform with early public-market earnings momentum.",
    ticker: "ASIC",
    postType: "pick",
    publishedAt: "2026-06-18",
    readingTime: 7,
  },
  {
    slug: "sofi-digital-banking-everything-app",
    title: "Stock buy: SoFi’s everything-app is delivering growth and real earnings",
    description: "SoFi is compounding members, products, and fee income across lending, deposits, and brokerage — with Q1 2026 showing record revenue and sustained profitability.",
    ticker: "SOFI",
    postType: "pick",
    publishedAt: "2026-06-05",
    readingTime: 8,
  },
  {
    slug: "roku-streaming-platform-advertising-engine",
    title: "Stock buy: Roku’s streaming platform is finally printing real profits",
    description: "Roku is the operating system of streaming for millions of households — and platform advertising plus subscriptions are now driving double-digit growth with expanding free cash flow.",
    ticker: "ROKU",
    postType: "pick",
    publishedAt: "2026-05-15",
    readingTime: 8,
  },
  {
    slug: "wt-wisdomtree-etf-and-digital-assets",
    title: "Stock buy: WisdomTree is compounding AUM across ETFs, privates, and digital",
    description: "WisdomTree is an asset manager with record AUM, a higher fee mix, and optionality in tokenized assets and private markets — a scaled compounder in a consolidating industry.",
    ticker: "WT",
    postType: "pick",
    publishedAt: "2026-05-01",
    readingTime: 7,
  },
  {
    slug: "atlc-inclusive-consumer-credit-platform",
    title: "Stock buy: Atlanticus is scaling inclusive credit with Mercury leverage",
    description: "Atlanticus enables partners to offer consumer credit to Everyday Americans — and the Mercury acquisition is amplifying an already profitable Credit-as-a-Service platform.",
    ticker: "ATLC",
    postType: "pick",
    publishedAt: "2026-04-17",
    readingTime: 8,
  },
  {
    slug: "sezl-buy-now-pay-later-platform-compounding",
    title: "Stock buy: Sezzle’s BNPL platform is compounding engagement and earnings",
    description: "Sezzle is turning buy-now-pay-later into a subscription-led consumer platform — with rising purchase frequency, expanding product surface, and raised 2026 earnings guidance.",
    ticker: "SEZL",
    postType: "pick",
    publishedAt: "2026-04-10",
    readingTime: 8,
  },
];

/**
 * The insight covering a ticker, if we have published one.
 *
 * Tolerates a null ticker: the anonymised payload served to non-subscribers
 * has no tickers, and it arrives as a 200 on the ordinary success path.
 */
export function getInsightByTicker(
  ticker: string | null | undefined,
): InsightIndexEntry | undefined {
  if (!ticker) return undefined;
  const upper = ticker.toUpperCase();
  return INSIGHT_INDEX.find(
    (i) => i.postType === "pick" && i.ticker?.toUpperCase() === upper,
  );
}

/** Metadata-only slug lookup, for server code that must not import article bodies. */
export function getInsightBySlugFromIndex(
  slug: string,
): InsightIndexEntry | undefined {
  return INSIGHT_INDEX.find((i) => i.slug === slug);
}

/** Insights covering any of these tickers, newest first. */
export function getInsightsForTickers(
  tickers: readonly (string | null | undefined)[],
): InsightIndexEntry[] {
  const wanted = new Set(
    tickers.filter((t): t is string => Boolean(t)).map((t) => t.toUpperCase()),
  );
  return INSIGHT_INDEX.filter(
    (i) => i.ticker !== null && wanted.has(i.ticker.toUpperCase()),
  );
}
